/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-email-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Email Code */
        post: operations["resend_email_code_v1_auth_resend_email_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Friends Route */
        get: operations["list_friends_route_v1_friends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Friend Route */
        post: operations["add_friend_route_v1_friends_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Friend Route */
        delete: operations["remove_friend_route_v1_friends__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/{user_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Friend Balance Route */
        get: operations["get_friend_balance_route_v1_friends__user_id__balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return liveness + build metadata.
         *
         *     No DDB / Cognito / external calls — this endpoint is invoked by the
         *     deploy smoke-test step and any external uptime monitor, so it must be
         *     cheap and side-effect-free.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete My Account Route
         * @description Soft-deactivate the current user.
         *
         *     Idempotent: a second call still returns 204. Cognito disable +
         *     global-sign-out fire on every call so a half-applied prior
         *     attempt heals on retry.
         */
        delete: operations["delete_my_account_route_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export My Data Route
         * @description JSON dump of the requester's data.
         *
         *     Rate-limited to one export per 24 h per user; subsequent calls
         *     return 429 ``RATE_LIMITED`` with ``retry_after`` in seconds.
         */
        get: operations["export_my_data_route_v1_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update My Profile Route
         * @description Update the requester's display name.
         *
         *     Email and currency are not editable from this endpoint and any
         *     extra body field is rejected (Pydantic ``extra="forbid"``).
         */
        patch: operations["update_my_profile_route_v1_me_profile_patch"];
        trace?: never;
    };
    "/telemetry/error": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Telemetry Event
         * @description Log a structured frontend telemetry event.
         *
         *     ``level=error`` lands at WARNING (an alert-worthy frontend
         *     crash), ``level=metric`` at INFO (one-shot performance sample).
         *
         *     Every free-text field is scrubbed of email / phone / JWT / AWS
         *     access-key shapes before logging. The ``extra`` dict is
         *     additionally key-name-redacted so a frontend that posts
         *     ``extra={"email": "x@y.com"}`` still emits ``"email":
         *     "[REDACTED]"`` in the log line.
         */
        post: operations["record_telemetry_event_v1_telemetry_error_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions Route */
        get: operations["list_transactions_route_v1_transactions_get"];
        put?: never;
        /** Create Transaction Route */
        post: operations["create_transaction_route_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{txn_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction Route */
        get: operations["get_transaction_route_v1_transactions__txn_id__get"];
        /**
         * Update Transaction Route
         * @description Edit an existing transaction.
         *
         *     The ``If-Match`` header carries the client's last-known
         *     ``updated_at`` (ISO 8601 with trailing ``Z``). A stale value
         *     surfaces as 412 ``PRECONDITION_FAILED`` — the client must
         *     refetch and retry. Re-uses the create-time validation surface.
         */
        put: operations["update_transaction_route_v1_transactions__txn_id__put"];
        post?: never;
        /**
         * Delete Transaction Route
         * @description Soft-delete. Idempotent — second call is a 204 no-op.
         *
         *     Creator-only (403 to non-creator member, 404 to non-member).
         */
        delete: operations["delete_transaction_route_v1_transactions__txn_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{txn_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comments Route */
        get: operations["list_comments_route_v1_transactions__txn_id__comments_get"];
        put?: never;
        /**
         * Post Comment Route
         * @description Post a user comment on the transaction.
         *
         *     404 (mask) for non-members. ``body`` is 1..1000 chars after trim.
         */
        post: operations["post_comment_route_v1_transactions__txn_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{txn_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Transaction Route
         * @description Restore a soft-deleted transaction within the 30-day window.
         *
         *     - 404 to non-members.
         *     - 403 to non-creator members.
         *     - 422 ``NOT_DELETED`` if the txn wasn't soft-deleted.
         *     - 410 ``GONE`` past the 30-day window.
         */
        post: operations["restore_transaction_route_v1_transactions__txn_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddFriendRequest
         * @description Payload for ``POST /v1/friends/add``.
         *
         *     ``email`` is permissive ``str`` here so the service layer can
         *     distinguish between a phone-shaped identifier (→ 400
         *     ``INVALID_IDENTIFIER`` per CLAUDE.md red-line 3) and a malformed
         *     email (→ 422 ``VALIDATION_ERROR``). Strict ``EmailStr`` would
         *     collapse both into 422, losing the distinction.
         *
         *     Phone is unverified-metadata-only on Cognito and is never used
         *     for lookup (CONSTRAINTS.md "email-only at MVP").
         */
        AddFriendRequest: {
            /** Email */
            email: string;
        };
        /**
         * AddFriendResponse
         * @description ``POST /v1/friends/add`` 200 response — same shape as a list row.
         */
        AddFriendResponse: {
            balance?: components["schemas"]["FriendBalanceSummary"] | null;
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** Name */
            name: string;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** User Id */
            user_id: string;
        };
        /**
         * Comment
         * @description One COMMENT row, rendered for the wire.
         */
        Comment: {
            /** Author Id */
            author_id: string;
            /** Body */
            body: string;
            /** Comment Id */
            comment_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "user" | "system";
            /** Txn Id */
            txn_id: string;
        };
        /**
         * CreateCommentRequest
         * @description ``POST /v1/transactions/{txn_id}/comments`` request body.
         */
        CreateCommentRequest: {
            /** Body */
            body: string;
        };
        /**
         * CreateTransactionRequest
         * @description ``POST /v1/transactions`` request body.
         *
         *     Structural validation only here — per-method invariants are in
         *     :func:`app.features.transactions.service.validate_create_payload`.
         */
        CreateTransactionRequest: {
            /** Amount */
            amount: number | string;
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** Members */
            members: components["schemas"]["MemberInput"][];
            /** Name */
            name: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Payers */
            payers: components["schemas"]["PayerInput"][];
            /**
             * Split Method
             * @enum {string}
             */
            split_method: "equal" | "amount" | "share" | "percent";
            /**
             * Txn Date
             * Format: date
             */
            txn_date: string;
            /**
             * Type
             * @enum {string}
             */
            type: "expense" | "settlement";
        };
        /**
         * ExportResponse
         * @description ``GET /v1/me/export`` 200 response.
         */
        ExportResponse: {
            /**
             * Exported At
             * Format: date-time
             */
            exported_at: string;
            /** Friendships */
            friendships: components["schemas"]["FriendshipExport"][];
            profile: components["schemas"]["MeProfile"];
            /** Transactions */
            transactions: components["schemas"]["TransactionExport"][];
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ForgotPasswordResponse */
        ForgotPasswordResponse: {
            /**
             * Status
             * @constant
             * @enum {string}
             */
            status: "RESET_CODE_SENT";
        };
        /**
         * FriendBalanceResponse
         * @description ``GET /v1/friends/{user_id}/balance`` 200 response.
         *
         *     Phase 3a returns the fully-typed shape with zeros / ``null`` so
         *     Phase 3b's UI can render the eventual balance card without
         *     re-architecting when Phase 4 wires real transaction aggregates.
         */
        FriendBalanceResponse: {
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** Last Transaction At */
            last_transaction_at?: string | null;
            /** Net */
            net: string;
            /**
             * Settlement Status
             * @enum {string}
             */
            settlement_status: "settled" | "friend_owes" | "you_owe";
            /** User Id */
            user_id: string;
        };
        /**
         * FriendBalanceSummary
         * @description Compact pair-balance shape carried on each ``FriendItem``.
         */
        FriendBalanceSummary: {
            /** Net */
            net: string;
            /**
             * Settlement Status
             * @enum {string}
             */
            settlement_status: "settled" | "friend_owes" | "you_owe";
        };
        /**
         * FriendItem
         * @description One row in the friends list — the friend's identity-safe shape.
         *
         *     ``balance`` is the requester-perspective net balance with the
         *     friend (sign convention matches :class:`FriendBalanceResponse`).
         *     Optional only because :class:`AddFriendResponse` reuses this shape
         *     on add — the add response doesn't compute a balance because it's
         *     always zero on a freshly-created friendship.
         */
        FriendItem: {
            balance?: components["schemas"]["FriendBalanceSummary"] | null;
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** Name */
            name: string;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** User Id */
            user_id: string;
        };
        /**
         * FriendshipExport
         * @description One friendship in the export.
         */
        FriendshipExport: {
            /** Friend User Id */
            friend_user_id: string;
            /**
             * Since
             * Format: date-time
             */
            since: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Env */
            env: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * ListCommentsResponse
         * @description ``GET /v1/transactions/{txn_id}/comments`` 200 body.
         */
        ListCommentsResponse: {
            /** Items */
            items: components["schemas"]["Comment"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ListFriendsResponse
         * @description ``GET /v1/friends`` 200 response.
         *
         *     ``next_cursor`` is opaque (HMAC-signed, requester-bound). When
         *     ``null`` the caller has reached the end of their friend list.
         */
        ListFriendsResponse: {
            /** Items */
            items: components["schemas"]["FriendItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ListTransactionsResponse */
        ListTransactionsResponse: {
            /** Items */
            items: components["schemas"]["TransactionListItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Id Token */
            id_token: string;
            /** Refresh Token */
            refresh_token?: string | null;
            user: components["schemas"]["LoginUser"];
        };
        /** LoginUser */
        LoginUser: {
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** Name */
            name: string;
            /** User Id */
            user_id: string;
        };
        /**
         * MeProfile
         * @description Trimmed user profile on the export. Only the fields we own
         *     server-side; raw email + phone come from Cognito and are not
         *     re-exposed here.
         */
        MeProfile: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** User Id */
            user_id: string;
        };
        /**
         * MeProfileSlim
         * @description ``PATCH /v1/me/profile`` 200 response.
         */
        MeProfileSlim: {
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** Name */
            name: string;
            /** User Id */
            user_id: string;
        };
        /**
         * Member
         * @description One member, with the server-computed ``owed_amount``.
         */
        Member: {
            /** Owed Amount */
            owed_amount: string;
            /** Percent */
            percent?: string | null;
            /** Share */
            share?: string | null;
            /** User Id */
            user_id: string;
        };
        /**
         * MemberInput
         * @description One member entry on a create request.
         */
        MemberInput: {
            /** Owed Amount */
            owed_amount?: number | string | null;
            /** Percent */
            percent?: number | string | null;
            /** Share */
            share?: number | string | null;
            /** User Id */
            user_id: string;
        };
        /** Payer */
        Payer: {
            /** Paid Amount */
            paid_amount: string;
            /** User Id */
            user_id: string;
        };
        /**
         * PayerInput
         * @description One payer entry on a create request.
         */
        PayerInput: {
            /** Paid Amount */
            paid_amount: number | string;
            /** User Id */
            user_id: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Id Token */
            id_token: string;
        };
        /** ResendEmailCodeRequest */
        ResendEmailCodeRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ResendEmailCodeResponse */
        ResendEmailCodeResponse: {
            /**
             * Status
             * @constant
             * @enum {string}
             */
            status: "RESENT";
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Code */
            code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** New Password */
            new_password: string;
        };
        /** ResetPasswordResponse */
        ResetPasswordResponse: {
            /** Password Reset */
            password_reset: boolean;
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
            /** Phone */
            phone?: string | null;
        };
        /** SignupResponse */
        SignupResponse: {
            /**
             * Status
             * @constant
             * @enum {string}
             */
            status: "PENDING_VERIFICATION";
            /** User Id */
            user_id: string;
        };
        /**
         * TelemetryAck
         * @description Trivial 202 acknowledgement so the client knows the event landed.
         */
        TelemetryAck: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
        };
        /**
         * TelemetryEvent
         * @description One frontend telemetry event.
         *
         *     ``level=error`` is for uncaught errors / unhandled promise
         *     rejections.  ``level=metric`` is for Core Web Vitals (LCP, INP,
         *     CLS, FID, TTFB) plus other custom dimensions.
         */
        TelemetryEvent: {
            /** Extra */
            extra?: {
                [key: string]: string | number | boolean | null;
            };
            /**
             * Level
             * @enum {string}
             */
            level: "error" | "metric";
            /**
             * Message
             * @default
             */
            message: string;
            /** Name */
            name: string;
            /**
             * Stack
             * @default
             */
            stack: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * User Agent
             * @default
             */
            user_agent: string;
            /** Value */
            value?: number | null;
        };
        /**
         * Transaction
         * @description ``POST /v1/transactions`` 201 + ``GET /v1/transactions/{id}`` 200.
         */
        Transaction: {
            /** Amount */
            amount: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Creator Id */
            creator_id: string;
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** Deleted At */
            deleted_at?: string | null;
            /** Members */
            members: components["schemas"]["Member"][];
            /** Name */
            name: string;
            /** Note */
            note: string;
            /** Payers */
            payers: components["schemas"]["Payer"][];
            /**
             * Split Method
             * @enum {string}
             */
            split_method: "equal" | "amount" | "share" | "percent";
            /**
             * Txn Date
             * Format: date
             */
            txn_date: string;
            /** Txn Id */
            txn_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "expense" | "settlement";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TransactionExport
         * @description One transaction (META + members + payers) in the export.
         */
        TransactionExport: {
            /** Amount */
            amount: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Creator Id */
            creator_id: string;
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** Deleted At */
            deleted_at?: string | null;
            /** Members */
            members: components["schemas"]["Member"][];
            /** Name */
            name: string;
            /** Note */
            note: string;
            /** Payers */
            payers: components["schemas"]["Payer"][];
            /**
             * Split Method
             * @enum {string}
             */
            split_method: "equal" | "amount" | "share" | "percent";
            /**
             * Txn Date
             * Format: date
             */
            txn_date: string;
            /** Txn Id */
            txn_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "expense" | "settlement";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TransactionListItem
         * @description One row in ``GET /v1/transactions`` — META + the requester's
         *     owed/paid amounts.
         *
         *     Both ``my_owed_amount`` and ``my_paid_amount`` are surfaced so the
         *     dashboard summary can compute ``net = paid - owed`` per transaction
         *     without an extra round-trip to read META payers. ``my_paid_amount``
         *     is the requester's slot in ``meta.payers`` (0.00 if they didn't pay).
         */
        TransactionListItem: {
            /** Amount */
            amount: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Creator Id */
            creator_id: string;
            /**
             * Currency
             * @enum {string}
             */
            currency: "USD" | "INR";
            /** My Owed Amount */
            my_owed_amount: string;
            /** My Paid Amount */
            my_paid_amount: string;
            /** Name */
            name: string;
            /**
             * Split Method
             * @enum {string}
             */
            split_method: "equal" | "amount" | "share" | "percent";
            /**
             * Txn Date
             * Format: date
             */
            txn_date: string;
            /** Txn Id */
            txn_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "expense" | "settlement";
        };
        /**
         * UpdateProfileRequest
         * @description ``PATCH /v1/me/profile`` request body.
         *
         *     Only the display ``name`` is mutable. Email and ``currency`` are
         *     intentionally absent and any extra field is rejected so that
         *     accidental client churn cannot rewrite them.
         */
        UpdateProfileRequest: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Code */
            code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** VerifyEmailResponse */
        VerifyEmailResponse: {
            /** Account Active */
            account_active: boolean;
            /** Email Verified */
            email_verified: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forgot_password_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: {
                "x-client-platform"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                rt?: string | null;
            };
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_email_code_v1_auth_resend_email_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendEmailCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResendEmailCodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyEmailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_friends_route_v1_friends_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFriendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_friend_route_v1_friends_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFriendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddFriendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_friend_route_v1_friends__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_friend_balance_route_v1_friends__user_id__balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendBalanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    delete_my_account_route_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_my_data_route_v1_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
        };
    };
    update_my_profile_route_v1_me_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeProfileSlim"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_telemetry_event_v1_telemetry_error_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_route_v1_transactions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                friend_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTransactionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_route_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_route_v1_transactions__txn_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                txn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_route_v1_transactions__txn_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                txn_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_route_v1_transactions__txn_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                txn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comments_route_v1_transactions__txn_id__comments_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                txn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCommentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_comment_route_v1_transactions__txn_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                txn_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_transaction_route_v1_transactions__txn_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                txn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
